# Generated by Django 4.2.2 on 2023-06-30 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals_management', '0002_goal_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_achievment', tinymce.models.HTMLField(blank=True, db_index=True, max_length=2000, null=True, verbose_name='goals_achievment')),
                ('goals_review', models.PositiveSmallIntegerField(choices=[(0, 'Nearly Meets Expectations'), (8, 'Meets Expectations'), (15, 'Exceeds Expectations')], db_index=True, default=0, verbose_name='goals_review')),
                ('teamwork', tinymce.models.HTMLField(blank=True, db_index=True, max_length=2000, null=True, verbose_name='teamwork')),
                ('teamwork_review', models.PositiveSmallIntegerField(choices=[(0, 'Nearly Meets Expectations'), (8, 'Meets Expectations'), (15, 'Exceeds Expectations')], db_index=True, default=0, verbose_name='teamwork_review')),
                ('innovation', tinymce.models.HTMLField(blank=True, db_index=True, max_length=2000, null=True, verbose_name='innovation')),
                ('innovation_review', models.PositiveSmallIntegerField(choices=[(0, 'Nearly Meets Expectations'), (8, 'Meets Expectations'), (15, 'Exceeds Expectations')], db_index=True, default=0, verbose_name='innovation_review')),
                ('work_ethics', tinymce.models.HTMLField(blank=True, db_index=True, max_length=2000, null=True, verbose_name='work_ethics')),
                ('work_ethics_review', models.PositiveSmallIntegerField(choices=[(0, 'Nearly Meets Expectations'), (8, 'Meets Expectations'), (15, 'Exceeds Expectations')], db_index=True, default=0, verbose_name='work_ethics_review')),
                ('total_review', models.PositiveSmallIntegerField(choices=[(0, 'Nearly Meets Expectations'), (8, 'Meets Expectations'), (15, 'Exceeds Expectations')], db_index=True, default=0, verbose_name='total_review')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewiews', to='goals_management.employee', verbose_name='employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_manager', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
