# Generated by Django 4.2.2 on 2023-07-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals_management', '0007_alter_manager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_manager', to='goals_management.manager', verbose_name='manager'),
        ),
    ]
