# Generated by Django 4.2.2 on 2023-07-07 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals_management', '0009_alter_review_goals_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, '🚀 High'), (1, '⚖ Medium'), (2, '🐢 Low')], db_index=True, default=0, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress',
            field=models.PositiveSmallIntegerField(choices=[(0, '🟣 0 %'), (1, '🟣 10 %'), (2, '🟠 20 %'), (3, '🟠 30 %'), (4, '🟠 40 %'), (5, '🟡 50 %'), (6, '🟡 60 %'), (7, '🟡 70 %'), (8, '🟢 80 %'), (9, '🟢 90 %'), (10, '🟢 100 %')], db_index=True, default=0, verbose_name='progress'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '📅 Planned'), (1, '⏳ In progress'), (2, '✅ Complete'), (3, '⏸️ On hold'), (4, '❌ Cancelled')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='GoalJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_date', models.DateTimeField(auto_now_add=True, verbose_name='updated date')),
                ('journal', models.TextField(max_length=4000, verbose_name='journal')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='goals_management.goal', verbose_name='goal')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_journals', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'goal journal',
                'verbose_name_plural': 'goal journals',
                'ordering': ['-journal_date'],
            },
        ),
    ]
