# Generated by Django 4.2.2 on 2023-07-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_management', '0010_alter_goal_priority_alter_goal_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='progress',
            field=models.PositiveSmallIntegerField(choices=[(0, '🟣 0 %'), (10, '🟣 10 %'), (20, '🟠 20 %'), (30, '🟠 30 %'), (40, '🟠 40 %'), (50, '🟡 50 %'), (60, '🟡 60 %'), (70, '🟡 70 %'), (80, '🟢 80 %'), (90, '🟢 90 %'), (100, '🟢 100 %')], db_index=True, default=0, verbose_name='progress'),
        ),
    ]
