# Generated by Django 4.2.2 on 2023-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_management', '0011_alter_goal_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date'),
        ),
    ]
