# Generated by Django 4.2.2 on 2023-06-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/pictures', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/pictures', verbose_name='picture'),
        ),
    ]
